on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Build and push package
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ingvord/axsis-gui

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build_args: NODE_AUTH_TOKEN=${{secrets.NODE_AUTH_TOKEN}}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}